//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradleyAquatics.Models
{
    using System;
    using System.Collections.Generic;

    public partial class tblOrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }

        

public virtual tblOrder tblOrder { get; set; }
        public virtual tblproduct tblproduct { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
